src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Author $author_id = null;

    #[ORM\OneToMany(mappedBy: 'book_id', targetEntity: BookCategory::class)]
    private Collection $categorie;

    #[ORM\Column]
    private ?bool $isRented = null;



    public function __construct()
    {
        $this->categorie = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getAuthorId(): ?Author
    {
        return $this->author_id;
    }

    public function setAuthorId(?Author $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    /**
     * @return Collection<int, BookCategory>
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(BookCategory $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie->add($categorie);
            $categorie->setBookId($this);
        }

        return $this;
    }

    public function removeCategorie(BookCategory $categorie): self
    {
        if ($this->categorie->removeElement($categorie)) {
            // set the owning side to null (unless already changed)
            if ($categorie->getBookId() === $this) {
                $categorie->setBookId(null);
            }
        }

        return $this;
    }

    public function isIsRented(): ?bool
    {
        return $this->isRented;
    }

    public function setIsRented(bool $isRented): self
    {
        $this->isRented = $isRented;

        return $this;
    }






}

src/Entity/BookRenting.php
<?php

namespace App\Entity;

use App\Repository\BookRentingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRentingRepository::class)]
class BookRenting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $renting_start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $renting_end = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $limit_date = null;

    #[ORM\ManyToOne(inversedBy: 'rents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Book $book_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getRentingStart(): ?\DateTimeInterface
    {
        return $this->renting_start;
    }

    public function setRentingStart(\DateTimeInterface $renting_start): self
    {
        $this->renting_start = $renting_start;

        return $this;
    }

    public function getRentingEnd(): ?\DateTimeInterface
    {
        return $this->renting_end;
    }

    public function setRentingEnd(\DateTimeInterface $renting_end): self
    {
        $this->renting_end = $renting_end;

        return $this;
    }

    public function getLimitDate(): ?\DateTimeInterface
    {
        return $this->limit_date;
    }

    public function setLimitDate(\DateTimeInterface $limit_date): self
    {
        $this->limit_date = $limit_date;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getBookId(): ?Book
    {
        return $this->book_id;
    }

    public function setBookId(?Book $book_id): self
    {
        $this->book_id = $book_id;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user_id', targetEntity: BookRenting::class)]
    private Collection $rents;

    #[ORM\Column(type: Types::ARRAY)]
    private array $roles = [];

    public function __construct()
    {
        $this->rents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection<int, BookRenting>
     */
    public function getRents(): Collection
    {
        return $this->rents;
    }

    public function addRent(BookRenting $rent): self
    {
        if (!$this->rents->contains($rent)) {
            $this->rents->add($rent);
            $rent->setUserId($this);
        }

        return $this;
    }

    public function removeRent(BookRenting $rent): self
    {
        if ($this->rents->removeElement($rent)) {
            // set the owning side to null (unless already changed)
            if ($rent->getUserId() === $this) {
                $rent->setUserId(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {


       return array_unique($this->roles);
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {

        return (string) $this->id;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reference')
            ->add('author_id')


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;
use App\Entity\Author;

use App\Entity\Book;
use App\Entity\BookRenting;
use App\Form\AuthorType;
use App\Form\BookType;
use App\Repository\AuthorRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\NotBlank;

class BookController extends AbstractController
{



    // Liste pour les livres montré aux utilisateurs
    #[Route('/books', 'books.list')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(Book::class);
        $books= $repository->findAll();

        $repository2 = $doctrine->getRepository(BookRenting::class);
        $bookrentings=$repository2->findAll();

        return $this->render('book/index.html.twig',
            ['books' => $books,
                'bookrentings' => $bookrentings
                ]);

    }

    #[Route('/admin/books', 'admin.books.list')]
    public function listlivre(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(Book::class);
        $books= $repository->findAll();


        return $this->render('admin/books/listBook.html.twig',
            ['books' => $books]);

    }


    // création de livre  par l'admin
    #[Route('/create/book','create.book')]
    public function createBook( Request $request,ManagerRegistry $doctrine)
    {
        $repository = $doctrine->getRepository(Author::class);
        $authors= $repository->findAll();
        $book = new Book();
        $form = $this->createFormBuilder($book)
            ->add('reference', TextType::class)

            //permet d'avoir la drop down avec les nom des auteurs
            ->add('author_id', EntityType::class,  [
                'class' => Author::class,
                'choice_label' => 'last_name' ,
                'placeholder' => ' Please choose a country',
                'query_builder' => function(AuthorRepository $repository) {
             return $repository->createQueryBuilder(' c ')->orderBy('c.last_name' , 'ASC');
                },
                'constraints' => new NotBlank([ 'message' => 'Choisir un auteur'])
            ])
            ->getForm();

        $form->handleRequest($request);

        // form submit
        if ($form->isSubmitted() && $form->isValid()) {

            $doctrine->getManager()->persist($book);
            $doctrine->getManager()->flush();
            return $this->redirectToRoute('admin.books.list');
        }

        return $this->render('admin/books/createbook.html.twig', [

            'form' => $form->createView(),
        ]);

    }

    //delete book
    #[Route('/book/delete/{id}','admin.book.delete')]
    public function deleteauthor(Request $request,Book $book,ManagerRegistry $doctrine) :Response
    {

        $doctrine->getManager()->remove($book);
        $doctrine->getManager()->flush();
        return $this->redirectToRoute(  'admin.books.list');
    }


    //modifier un livre
    #[Route('/admin/book/edit/{id}','admin.book.edit')]
    public function editbook( Request $request,Book $book,ManagerRegistry $doctrine):Response
    {

        $form = $this->createFormBuilder($book)
            ->add('reference', TextType::class)
            ->add('author_id', EntityType::class,  [
                'class' => Author::class,
                'choice_label' => 'last_name' ,
                'placeholder' => ' Choisir un auteur',
                'query_builder' => function(AuthorRepository $repository) {
                    return $repository->createQueryBuilder(' c ')->orderBy('c.last_name' , 'ASC');
                },
                'constraints' => new NotBlank([ 'message' => 'Choisir un auteur'])
            ])

            ->getForm();



        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $doctrine->getManager()->persist($book);
            $doctrine->getManager()->flush();
            return $this->redirectToRoute('admin.books.list');
        }

        return $this->render('admin/books/createbook.html.twig', [

            'form' => $form->createView(),
        ]);

    }

}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}


    <table  class=" mt-4 table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <h1>
        Livre disponible à la location
        </h1>
        <tr>
            <th>id</th>
            <th>reference</th>
            <th>auteur</th>
            <th>louer</th>

        </tr>
        </thead>
        <tbody>
                    {% for book in books %}

                             {% if book.isRented == false %}
                                            <tr>

                                                <td>
                                                    <p class="fw-normal mb-1">{{ book.id }}</p>

                                                </td>

                                                <td>
                                                    <p class="fw-normal mb-1">{{ book.reference }} </p>
                                                </td>
                                                <td>
                                                    <p class="fw-normal mb-1">{{  book.authorid.lastname }} {{  book.authorid.firstname }}</p>
                                                </td>

                                                <td>

       <!-- renvoie l'utilisateur vers la page de connexion si il n'est pas connecté et essaye d'acceder à la page de prêt  -->
                                                    <a
                                                            {% if app.user ==true %}
                                                            href="/book/renting/{{ book.id }}"
                                                            {% else %}
                                                                href="/login"
                                                                {% endif %}
                                                            class="card-link">
                                                        <button type="button" class="btn btn-primary">
                                                            Louer
                                                        </button>
                                                    </a>
                                                </td>
                                            </tr>

                                {% endif %}
                    {% endfor %}



        </tbody>
    </table>


{% endblock %}

templates/book/mesLivres.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>
        Livre en cour de location
    </h1>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
    <tr>
        <th>id Livre</th>
        <th>reference</th>
        <th>author</th>
        <th>Date emprunt</th>
        <th>Date de remise</th>
        <th>Modification</th>

    </tr>
    </thead>
    <tbody>
    {% for booksrenting in booksrentings %}

        <!--   Affiche que les livres de l'utilisateur connecté -->
             {% if booksrenting.userId.id == app.user.userIdentifier %}
            <tr>

                <td>
                    <p class="fw-normal mb-1">{{ booksrenting.bookid.id }}</p>

                </td>

                <td>
                    <p class="fw-normal mb-1">{{ booksrenting.bookid.reference }} </p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{  booksrenting.bookid.authorId.firstName }}</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{  booksrenting.rentingStart|date("d/m/Y") }}</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{  booksrenting.rentingEnd|date_modify("+30 day")|date("d/m/Y")  }}</p>
                </td>

                <td>
                    <a href="/rendrelivre/{{ booksrenting.id }}" class="card-link">
                        <button type="button" class="btn btn-primary">
                            Rendre le livre
                        </button>
                    </a>
                </td>
            </tr>

            {% endif %}
    {% endfor %}
        </tbody>
        </table>




{% endblock %}